name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated

      - name: Set up Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/70705/nixvim-config.git

      - name: Commit and push changes
        run: |
          git add flake.lock
          git commit -m "Update flake.lock" || exit 0
          git push --force-with-lease origin update_flake_lock_action:refs/heads/update_flake_lock_action

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Update flake.lock"
          branch: update_flake_lock_action
          title: "Update flake.lock"
          labels: dependencies, automated
          assignees: github-actions[bot]
          reviewers: [ ]

      - name: Merge Pull Request
        if: success()
        uses: ahmadnassri/action-auto-merge@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          merge-method: squashdate_flake_lock_action:refs/heads/update_flake_lock_action
